services:
  - type: web
    name: strapi-app
    env: node
    plan: free  # یا 'starter' برای منابع بهتر
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: APP_KEYS
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
